project:
  type: website
  output-dir: docs

website:
  title: "Fintech533_Pinya713"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: breakout.qmd
        text: Breakout Strategy

format:
  html:
    theme: darkly
    css: styles.css
    toc: true


