project:
  type: website
  output-dir: docs

website:
  title: "Fintech533_Pinya713"
  site-url: "https://pinyatrading.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: breakout.qmd
        text: Breakout Strategy
      - href: final_project.qmd
        text: Final Project

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

